apiVersion: apps/v1
kind: Deployment
metadata:
  name: commentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commentservice
  template:
    metadata:
      labels:
        app: commentservice
    spec:
      containers:
        - name: commentservice
          image: commentservice:latest # Use your built image tag
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: commentservice
spec:
  selector:
    app: commentservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080