apiVersion: apps/v1
kind: Deployment
metadata:
  name: manuscryptgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manuscryptgateway
  template:
    metadata:
      labels:
        app: manuscryptgateway
    spec:
      containers:
        - name: manuscryptgateway
          image: manuscryptgateway:latest # Use your built image tag
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: manuscryptgateway
spec:
  selector:
    app: manuscryptgateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer