apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriptionservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriptionservice
  template:
    metadata:
      labels:
        app: subscriptionservice
    spec:
      containers:
        - name: subscriptionservice
          image: subscriptionservice:latest # Use your built image tag
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: subscriptionservice
spec:
  selector:
    app: subscriptionservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080